export const ADDTASK = 'ADDTASK';
export const DELETECOMPLETEDTASK = 'DELETECOMPLETEDTASK';
export const DELETEALLTASK = 'DELETEALLTASK';
export const TOGGLECOMPLETED = 'TOGGLECOMPLETED';
export const EDITTITLE = 'EDITTITLE';
export const EDITDESCRIPTION = 'EDITDESCRIPTION';

